### ISSUE TITLE
ImportError in Python (NNSplit)

### ISSUE THREAD

**Issue by albertovilla** [bminixhofer/nnsplit#45]
Hi, I was trying the simple example in Python from the documentation and I'm getting an `ImportError`:

```python
from nnsplit import NNSplit
splitter = NNSplit.load("en")

# returns `Split` objects
splits = splitter.split(["This is a test This is another test."])[0]

# a `Split` can be iterated over to yield smaller splits or stringified with `str(...)`.
for sentence in splits:
   print(sentence)
```` 

When executing this example I'm getting the following error:

```
Traceback (most recent call last):
  File "nnsplit.py", line 1, in <module>
    from nnsplit import NNSplit
  File "G:\OneDrive\projects\s\nnsplit.py", line 1, in <module>
    from nnsplit import NNSplit
ImportError: cannot import name 'NNSplit' from partially initialized module 'nnsplit' (most likely due to a circular import) (G:\OneDrive\projects\s\nnsplit.py)
```

I have installed the packages in a new conda environment, executing `pip list installed` I have:

```
pip list installed
Package         Version
--------------- -------------------
certifi         2020.12.5
nnsplit         0.5.7.post0
numpy           1.20.3
onnxruntime     1.7.0
onnxruntime-gpu 1.7.0
pip             21.1.1
protobuf        3.17.1
setuptools      52.0.0.post20210125
six             1.16.0
tqdm            4.61.0
wheel           0.36.2
wincertstore    0.2
```

**Comment by bminixhofer** [comment]
Hi, thanks for the issue!

I believe the problem is that the file is named `nnsplit.py`, can you try renaming it? I just tried using numpy in a file called `numpy.py` and get the same error, so I don't think this is a bug in nnsplit.

**Comment by albertovilla** [comment]
Hi Benajamin, I think that was an issue on my side... I put that name on the file temporarily and I didn't change it :) 
Now, the example works, thanks a lot.
